version: '2'
services:
  web:
    image: pdahlstrom/flask-docker-example:latest

  mysql:
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: host=host1
