version: '2'
services:
  web:
    build: .
    links:
      - redis
      - mysql
    environment:
      - FLASK_APP=app.py
      - FLASK_HOST=0.0.0.0

  redis:
    image: redis

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
