version: '2'
services:
  web:
    upgrade_strategy:
      start_first: true
    labels:
      io.rancher.scheduler.affinity:host_label:: host=host1
    scale: 2
  
  redis:
    labels:
      io.rancher.scheduler.affinity:host_label:: host=host1